apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
spec:
  selector:
    matchLabels:
      run: scanner
  replicas: 1
  template:
    metadata:
      labels:
        run: scanner
    spec:
      containers:
      - name: scanner
        command:
          - /scanner
          - --db=example:example@tcp(mariadb)/collekt?parseTime=True
        image: scanner
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroll
spec:
  selector:
    matchLabels:
      run: enroll
  replicas: 1
  template:
    metadata:
      labels:
        run: enroll
    spec:
      containers:
      - name: enroll
        command:
          - /enroll
          - -scanner=http://scanner:8080
        image: enroll
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect
spec:
  selector:
    matchLabels:
      run: collect
  replicas: 1
  template:
    metadata:
      labels:
        run: collect
    spec:
      containers:
      - name: collect
        image: collect
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
          - name: perftank
            mountPath: /persistent
        command:
          - /collect
          - -port=8080
          - -scanner=http://scanner:8080
          - -enroll=http://enroll:8080
          - -extract=http://extract:8080
          - -db=example:example@tcp(mariadb)/collekt?parseTime=True
          - -persistent=/persistent
          - -volatile=/persistent/volatile
          - -flamescope=http://flamescope.internal.worksap.com/#/heatmap/
      volumes:
        - name: perftank
          persistentVolumeClaim:
            claimName: perftank-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
spec:
  selector:
    matchLabels:
      run: static
  replicas: 1
  template:
    metadata:
      labels:
        run: static
    spec:
      containers:
      - name: static
        image: static
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blame
spec:
  selector:
    matchLabels:
      run: blame
  replicas: 1
  template:
    metadata:
      labels:
        run: blame
    spec:
      containers:
      - name: blame
        image: blame
        ports:
        - containerPort: 8080
        command:
          - /blame
          - -nSearchWorker=8
        imagePullPolicy: Always
