image: golang:1.9

before_script:
    - mkdir -p /go/src/git.paas.workslan/resource_optimization
    - ln -s ${CI_PROJECT_DIR} /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
    - ls
    - ls /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
    - cd /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
    - curl https://github.com/go-swagger/go-swagger/releases/download/0.15.0/swagger_linux_amd64 > /go/bin/swagger
    - chmod +x /go/bin/swagger
    - swagger generate server -f api/collect.yml -t generated_files -A collect

build:
    stage: build
    script:
        - make dep
        - make
