backend-build:
    stage: build
    image: golang:1.9
    script:
        - mkdir -p /go/src/git.paas.workslan/resource_optimization
        - ln -s ${CI_PROJECT_DIR} /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
        - cd /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
        - curl -sS https://github.com/go-swagger/go-swagger/releases/download/0.15.0/swagger_linux_amd64 -L > /go/bin/swagger
        - chmod +x /go/bin/swagger
        - swagger generate server -f api/collect.yml -t generated_files -A collect
        - make dep
        - make backend

front-build:
    stage: build
    image: node:10.8.0
    script:
        - yarn add --dev webpack webpack-cli
        - PATH=$PATH:/node_modules/.bin make front
