image: golang:1.9

before_script:
    - mkdir -p /go/src/git.paas.workslan/resource_optimization/dynamic_analysis
    - ln -s /go/src/git.paas.workslan/resource_optimization/dynamic_analysis $CI_PROJECT_DIR
    - make dep

build:
    stage: build
    script:
        - make
