matrix:
  include:
    - language: node_js
      node_js: "lts/*"
      cache: yarn
      before_script:
        - java -jar ./openapi-generator-cli.jar generate -i ./api/collect.yml -g typescript-fetch -o ./front/src/generated/collect -D modelPropertyNaming=original
        - make openapi-client-gen
        - cd front
        - yarn install
      script:
        - yarn test
        - yarn lint
        - yarn build # only for check and not for deploy