matrix:
  include:
    - language: go
      go: "1.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      before_script:
        - curl -sS https://github.com/go-swagger/go-swagger/releases/download/v0.17.2/swagger_linux_amd64 -L > /usr/local/bin
        - chmod +x /usr/local/bin/swagger
        - make swagger
      script:
        - make dep
        - make backend
    - language: node_js
      node_js: "lts/*"
      cache: yarn
      before_script:
        - wget http://central.maven.org/maven2/org/openapitools/openapi-generator-cli/3.3.4/openapi-generator-cli-3.3.4.jar -O openapi-generator-cli.jar
        - make openapi-client-gen
        - cd front
        - yarn install
      script:
        - yarn test
        - yarn lint
        - yarn build # only for check and not for deploy