PKG = $(shell find pkg -name *.go)


.PHONY: default clean fmt make_stub dep swagger backend front test

default: all

all: front backend

backend: bin/scanner bin/collect bin/enroll bin/blame
front: front/public/app.js

collect: collect-img

bin/enroll: $(shell find cmd/enroll -name *.go) $(PKG)
	CGO_ENABLED=0 go build -o bin/enroll cmd/enroll/*.go

bin/blame: $(shell find cmd/blame -name *.go) $(PKG)
	CGO_ENABLED=0 go build -o bin/blame cmd/blame/*.go

bin/collect: $(shell find cmd/collect -name *.go) $(PKG) generated_files/stub
	CGO_ENABLED=0 go build -o bin/collect cmd/collect/*.go

bin/scanner: $(shell find cmd/scanner -name *.go) $(PKG)
	CGO_ENABLED=0 go build -o bin/scanner cmd/scanner/*.go

swagger:
	swagger generate server -f api/collect.yml -t generated_files -A collect

generated_files/stub: api/collect.yml
	swagger generate server -f api/collect.yml -t generated_files -A collect
	touch generated_files/stub

swagger-client-gen:
	java -jar ./swagger-codegen-cli.jar generate -i ./api/collect.yml -l typescript-fetch -o ./front/src/generated/collect -D modelPropertyNaming=original
	java -jar ./swagger-codegen-cli.jar generate -i ./api/blame.yml -l typescript-fetch -o ./front/src/generated/blame -D modelPropertyNaming=original

swagger-mock-gen:
	java -jar ./swagger-codegen-cli.jar generate -i ./api/collect.yml -l nodejs-server -o ./front/mock/collect
	java -jar ./swagger-codegen-cli.jar generate -i ./api/blame.yml -l nodejs-server -o ./front/mock/suspect

front/public/app.js:
	cd front && yarn build

make_stub:
	@echo This directory is intended to be kept empty and reserved for data generated by build tools > generated_files/stub

clean:
	\rm -r front/public/; rm -r bin/; rm -r generated_files/cmd; rm -r generated_files/models; rm -r generated_files/restapi; rm generated_files/stub

fmt:	
	go fmt ./cmd/...
	go fmt ./pkg/...

test:
	go test ./cmd/...
	go test ./pkg/...

dep:
	go get -t -v -d ./...
