declare const COLLECT_API_BASE: string;
declare const FLAMESCOPE_API_BASE: string;
declare const APP_NAME: string;

const _COLLECT_API_BASE = COLLECT_API_BASE;
const _FLAMESCOPE_API_BASE = FLAMESCOPE_API_BASE;
const _APP_NAME = APP_NAME;
export {
  _COLLECT_API_BASE as COLLECT_API_BASE,
  _FLAMESCOPE_API_BASE as FLAMESCOPE_API_BASE,
  _APP_NAME as APP_NAME
};
