apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
spec:
  template:
    spec:
      containers:
      - name: scanner
        image: ${DOCKERREG}/scanner:${GIT_HASH}
        command:
          - /scanner
          - -logLocation=$INTERNAL_LOG_LOCATION
          - -db=$DB_CRED_USER:$DB_CRED_PASS@tcp(mariadb)/collekt?parseTime=True
          - -logTempl=$INTERNAL_LOG_TEMPL
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect
spec:
  template:
    spec:
      containers:
      - name: collect
        image: ${DOCKERREG}/collect:${GIT_HASH}
        command:
          - /collect
          - -port=8080
          - -scanner=http://scanner:8080
          - -enroll=http://enroll:8080
          - -extract=http://extract:8080
          - -db=$DB_CRED_USER:$DB_CRED_PASS@tcp(mariadb)/collekt?parseTime=True
          - -persistent=/persistent
          - -volatile=/persistent/volatile
          - -flamescope=http://flamescope.internal.worksap.com/#/heatmap/
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blame
spec:
  template:
    spec:
      containers:
      - name: blame
        image: ${DOCKERREG}/blame:${GIT_HASH}
        command:
          - /blame
          - -searchUrl=$INTERNAL_SEARCH_SERVER
          - -searchPost=$INTERNAL_SEARCH_POST
          - -searchType=internal-use
          - -nSearchWorker=8

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enroll
spec:
  template:
    spec:
      containers:
      - name: enroll
        image: ${DOCKERREG}/enroll:${GIT_HASH}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
spec:
  template:
    spec:
      containers:
      - name: static
        image: ${DOCKERREG}/static:${GIT_HASH}
