swagger: '2.0'
info:
  version: '0.1'
  title: 'collective server for performance inspection'

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:
  app:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        minLength: 4
      landscape:
        type: array
        items:
          $ref: "#/definitions/landscape"

  landscape:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        minLength: 4
      pods:
        type: array
        items:
          $ref: "#/definitions/pod"
      live_count:
          type: integer

  pod:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        minLength: 4
      snapshots:
        type: array
        items:
          $ref: "#/definitions/snapshot_summary"
      is_live:
        type: boolean
      created_at:
        type: string
        format: date-time

  snapshot_summary:
    type: object
    required:
      - id 
    properties:
      id:
        type: string
        minLength: 4
      created_at:
        type: string
        format: date-time

  replicas_request:
    type: object
    required:
      - count
    properties:
      count:
        type: integer


paths:
  /apps:
    get:
      responses:
        200:
          description: |
            "this returns list of apps"
          schema:
            type: array
            items:
              $ref: "#/definitions/app"
  /apps/{appid}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes app"
          schema:
            $ref: "#/definitions/app"
              
  /apps/{appid}/landscapes:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of landscapes"
          schema:
            type: array
            items:
              $ref: "#/definitions/landscape"

  /apps/{appid}/landscapes/{landscape}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: landscape
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the landscape"
          schema:
            $ref: "#/definitions/landscape"
    patch:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: landscape
          type: string
          in: path
          required: true
        - name: replicas
          in: body
          schema:
            $ref: "#/definitions/replicas_request"
      responses:
        200:
          description: |
            "this changes the number of perf-ing replicas of app/landscape"
          schema:
            $ref: "#/definitions/landscape"

  /apps/{appid}/landscapes/{landscape}/pods:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: landscape
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of pods"
          schema:
            type: array
            items:
              $ref: "#/definitions/pod"

  /apps/{appid}/landscapes/{landscape}/pods/{pod}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: landscape
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the pod"
          schema:
            $ref: "#/definitions/pod"
          #  /apps/{appid}/landscapes: {}
          #  /apps/{appid}/landscapes/{landscapeid}: {}
          #/apps/{appid}/landscapes/{landscapeid}/pods: {}
          #/apps/{appid}/landscapes/{landscapeid}/pods/{pods}:
          #get: {}
          #patch: {}
