swagger: '2.0'
info:
  version: '0.1'
  title: 'collective server for performance inspection'

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  environment-config:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      tenant:
        type: string
      version:
        type: string
      landscape:
        type: string
      mischoUrl:
        type: string
      serviceUrl:
        type: string
      kubernetesApi:
        type: string
      isMultitenant:
        type: boolean
      isEnabled:
        type: boolean

  app:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      environments:
        type: array
        items:
          $ref: "#/definitions/environment"
      lastseen:
        type: string
        format: date-time

  environment:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      pods:
        type: array
        items:
          $ref: "#/definitions/pod"
      liveCount:
          type: integer

  pod:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      snapshots:
        type: array
        items:
          $ref: "#/definitions/snapshot"
      isAlive:
        type: boolean
      createdAt:
        type: string
        format: date-time
      app:
        type: string
      environment:
        type: string

  snapshot:
    type: object
    required:
      - uuid 
    properties:
      uuid:
        type: string
        minLength: 36
        maxLength: 36
      createdAt:
        type: string
        format: date-time
      pod:
        type: string
      environment:
        type: string
      flamescopeLink:
        type: string
    example:
      uuid: "d7eec7c1-daf5-4198-9503-6957aea0bf90"
      createdAt: "2018-01-15T03:00:00.000Z"
      pod: "collabo"
      environment: "systema"
      flamescopeLink: "http://flamescope.internal.worksap.com/#/heatmap/collabo-bd6dc859c-f7dfm%2Fa0%2Fd7eec7c1-daf5-4198-9503-6957aea0bf90"

  replicasRequest:
    type: object
    required:
      - count
    properties:
      count:
        type: integer

paths:
  /healthz:
    get:
      responses:
        200:
          description: "For readiness probe"
          schema:
            type: string
      operationId: healthz

  /apps:
    get:
      responses:
        200:
          description: |
            "this returns list of name of apps"
          schema:
            type: array
            items:
              type: string
      operationId: getApps

  /apps/{appid}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes app"
          schema:
            $ref: "#/definitions/app"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
      operationId: describeApp
              
  /apps/{appid}/environments:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of environments"
          schema:
            type: array
            items:
              $ref: "#/definitions/environment"
      operationId: getEnvironments

  /apps/{appid}/environments/{environment}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the environment"
          schema:
            $ref: "#/definitions/environment"
      operationId: describeEnvironment
    patch:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: replicas
          in: body
          schema:
            $ref: "#/definitions/replicasRequest"
      responses:
        200:
          description: |
            "this changes the number of perf-ing replicas of app/environment"
          schema:
            $ref: "#/definitions/environment"

  /apps/{appid}/environments/{environment}/pods:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of pods"
          schema:
            type: array
            items:
              $ref: "#/definitions/pod"
      operationId: getPods

  /apps/{appid}/environments/{environment}/pods/{pod}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the pod"
          schema:
            $ref: "#/definitions/pod"
      operationId: describePod

  /apps/{appid}/environments/{environment}/pods/{pod}/snapshots:
    post:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this makes a new snapshot"
          schema:
            $ref: "#/definitions/snapshot"
      operationId: newSnapshot
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this shows snapshots"
          schema:
            type: array
            items:
              $ref: "#/definitions/snapshot"
      operationId: listSnapshots

  /available-pods:
    get:
      responses:
        200:
          description: |
            "this shows list of currently perf-enabled pods"
          schema:
            type: array
            items:
              $ref: "#/definitions/pod"
      operationId: listAvailablePods

  /config:
    get:
      responses:
        200:
          description: |
            "Show possible configs"
          schema:
            type: array
            items:
              type: string
      operationId: getConfig 

  /config/environments:
    get:
      responses:
        200:
          description: |
            "list the environments to be scanned"
          schema:
            type: array
            items:
              $ref: "#/definitions/environment-config"
      operationId: listEnvironmentConfig
    post:
      parameters:
        - name: config
          in: body
          schema:
            $ref: "#/definitions/environment-config"
      responses:
        200:
          description: |
            "replace the configuration of this environment"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: addEnvironmentConfig

  /config/environments/{environment}:
    get:
      parameters:
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "describe the environment configuration"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: describeEnvironmentConfig
    put:
      parameters:
        - name: environment
          type: string
          in: path
          required: true
        - name: config
          in: body
          schema:
            $ref: "#/definitions/environment-config"
      responses:
        200:
          description: |
            "replace the configuration of this environment"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: putEnvironmentConfig

