swagger: '2.0'
info:
  version: '0.1'
  title: 'collective server for performance inspection'

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  app:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      environments:
        type: array
        items:
          $ref: "#/definitions/environment"
      lastseen:
        type: string
        format: date-time

  environment:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      pods:
        type: array
        items:
          $ref: "#/definitions/pod"
      live_count:
          type: integer

  pod:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
        minLength: 4
      snapshots:
        type: array
        items:
          $ref: "#/definitions/snapshot_summary"
      is_live:
        type: boolean
      created_at:
        type: string
        format: date-time

  snapshot_summary:
    type: object
    required:
      - uuid 
    properties:
      uuid:
        type: string
        minLength: 36
        maxLength: 36
      created_at:
        type: string
        format: date-time

  snapshot:
    type: object
    required:
      - uuid 
    properties:
      uuid:
        type: string
        minLength: 36
        maxLength: 36
      created_at:
        type: string
        format: date-time
      pod:
        type: string
      environment:
        type: string
      flamescope_link:
        type: string

  replicas_request:
    type: object
    required:
      - count
    properties:
      count:
        type: integer

  config:
    type: object
    required:
      - date
    properties:
      date:
        type: string
        format: date-time
      environment-config:
        type: array
        items:
          $ref: "#/definitions/environment-config"

  environment-config:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      tenant:
        type: string
      version:
        type: string
      landscape:
        type: string
      mischo-url:
        type: string
      service-url:
        type: string
      is_multitenant:
        type: boolean

paths:
  /healthz:
    get:
      responses:
        200:
          description: "For readiness probe"
          schema:
            type: string
      operationId: healthz

  /apps:
    get:
      responses:
        200:
          description: |
            "this returns list of apps"
          schema:
            type: array
            items:
              $ref: "#/definitions/app"
      operationId: getApps

  /apps/{appid}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes app"
          schema:
            $ref: "#/definitions/app"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
      operationId: describeApp
              
  /apps/{appid}/environments:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of environments"
          schema:
            type: array
            items:
              $ref: "#/definitions/environment"
      operationId: getEnvironments

  /apps/{appid}/environments/{environment}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the environment"
          schema:
            $ref: "#/definitions/environment"
      operationId: describeEnvironment
    patch:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: replicas
          in: body
          schema:
            $ref: "#/definitions/replicas_request"
      responses:
        200:
          description: |
            "this changes the number of perf-ing replicas of app/environment"
          schema:
            $ref: "#/definitions/environment"

  /apps/{appid}/environments/{environment}/pods:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this returns list of pods"
          schema:
            type: array
            items:
              $ref: "#/definitions/pod"
      operationId: getPods

  /apps/{appid}/environments/{environment}/pods/{pod}:
    get:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the pod"
          schema:
            $ref: "#/definitions/pod"
      operationId: describePod

  /apps/{appid}/environments/{environment}/pods/{pod}/snapshots:
    post:
      parameters:
        - name: appid
          type: string
          in: path
          required: true
        - name: environment
          type: string
          in: path
          required: true
        - name: pod
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this makes a new snapshot"
          schema:
            $ref: "#/definitions/snapshot"
      operationId: newSnapshot

  /config:
    get:
      responses:
        200:
          description: |
            "this shows configuration overview"
          schema:
            $ref: "#/definitions/config"
      operationId: getConfigs

  /config/environment/{environment}:
    get:
      parameters:
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "this describes about the pod"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: getEnvironmentConfig
