swagger: '2.0'
info:
  version: '0.1'
  title: 'collective server for performance inspection'

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  config:
    type: object
    required:
      - date
    properties:
      date:
        type: string
        format: date-time
      environment-config:
        type: array
        items:
          $ref: "#/definitions/environment-config"

  environment-config:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      tenant:
        type: string
      version:
        type: string
      landscape:
        type: string
      mischo-url:
        type: string
      service-url:
        type: string
      kube-api:
        type: string
      is_multitenant:
        type: boolean

paths:
  /healthz:
    get:
      responses:
        200:
          description: "For readiness probe"
          schema:
            type: string
      operationId: healthz
  /config:
    get:
      responses:
        200:
          description: |
            "this shows configuration overview"
          schema:
            $ref: "#/definitions/config"
      operationId: getConfigs

  /config/environment:
    get:
      responses:
        200:
          description: |
            "list the environments to be scanned"
          schema:
            type: array
            items:
              $ref: "#/definitions/environment-config"
      operationId: listEnvironmentConfig
    post:
      parameters:
        - name: config
          in: body
          schema: $ref "#/definitions/environment-config"
      responses:
        200:
          description: |
            "replace the configuration of this environment"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: postEnvironmentConfig

  /config/environment/{environment}:
    get:
      parameters:
        - name: environment
          type: string
          in: path
          required: true
      responses:
        200:
          description: |
            "describe the environment configuration"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: describeEnvironmentConfig
    put:
      parameters:
        - name: environment
          type: string
          in: path
          required: true
        - name: config
          in: body
          schema: $ref "#/definitions/environment-config"
      responses:
        200:
          description: |
            "replace the configuration of this environment"
          schema:
            $ref: "#/definitions/environment-config"
      operationId: putEnvironmentConfig

